# Docker Compose file for MEAN stack application as prod mode images will load from docker hub.
# Define the services/containers to be run
services:
  angular: # name of the first service
    image: nitin27may/mean-angular:latest # specify image to build container from
    container_name: ${ID_PROJECT:-mean}_angular
    restart: always
    ports:
      - "4000:4000" # specify port forewarding
    environment:
      - NODE_ENV=dev
    links: 
      - express 

  express: #name of the second service
    image: nitin27may/mean-expressjs:latest # specify image to build container from
    container_name: ${ID_PROJECT:-mean}_express
    restart: always
    ports:
      - "3000:3000" #specify ports forewarding
      # Below database enviornment variable for api is helpful when you have to use database as managed service
    environment:
      - SECRET=${SECRET}
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_HOST=${MONGO_DB_HOST}
      - MONGO_DB_PORT=${MONGO_DB_PORT}
      - MONGO_DB_PARAMETERS=${MONGO_DB_PORT}
      - MONGO_DB_DATABASE=${MONGO_DB_DATABASE}  
      - EXPRESS_PORT=${MONGO_DB_DATABASE}
    links:
      - database

  database: # name of the third service
    image: mongo:latest # specify image to build container from
    container_name: ${ID_PROJECT:-mean}_mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB=${MONGO_DB_DATABASE}
      - MONGO_INITDB_DATABASE=${MONGO_DB_DATABASE} 
    volumes:
      - ./mongo:/home/mongodb
      - ./mongo/init-db.d/:/docker-entrypoint-initdb.d/
      - ./mongo/db:/data/db
    ports:
      - "27017:27017" # specify port forewarding

  nginx: #name of the fourth service
    image: nitin27may/mean-nginx # specify image to build container from
    container_name: ${ID_PROJECT:-mean}_nginx
    restart: always
    ports:
      - "80:80" #specify ports forewarding
    links:
      - express
      - angular
