title: MEAN (Docker)
description: A full-featured contact management application built with TypeScript-powered MEAN stack with Docker Support.
remote_theme: just-the-docs/just-the-docs

url: https://nitin27may.github.io/mean-docker

# Enable support for hyphenated search keywords
search_tokenizer_separator: /[\s/]+/

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "//github.com/nitin27may/mean-docker"

# Footer content
footer_content: "Copyright &copy; 2025 Nitin Singh. Distributed by an MIT license."

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Add spacing to fix title cropping issue
heading_anchors: true

# Fixed spacing configuration
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    color: blue
  new:
    color: green
  note:
    color: purple
  warning:
    color: red

# Set the proper spacing (this is the correct format)
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
  
# Add custom CSS for spacing
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/nitin27may/mean-docker"
gh_edit_branch: "master"
gh_edit_view_mode: "tree"

# Enable navigation structure
nav_external_links:
  - title: MEAN Stack Contacts on GitHub
    url: https://github.com/nitin27may/mean-docker
    hide_icon: false

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Enable collapsible navigation
collapse_inactive_chapters: true

# Enable copy code button
enable_copy_code_button: true
# Google Analytics Tracking (optional)
ga_tracking: G-S7CCY33H9D
ga_tracking_anonymize_ip: true

