version: '3.8'

services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: contact-api
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - PORT=3000
  #     - SECRET=${SECRET}
  #     - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
  #     - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
  #     - MONGO_DB_HOST=database
  #     - MONGO_DB_PORT=${MONGO_DB_PORT}
  #     - MONGO_DB_PARAMETERS=${MONGO_DB_PARAMETERS}
  #     - MONGO_DB_DATABASE=${MONGO_DB_DATABASE}
  #     - NODE_ENV=production
  #   depends_on:
  #     - database
  #   networks:
  #     - contact-network

  database:
    image: mongo:latest
    container_name: contact-mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB=${MONGO_DB_DATABASE}
    volumes:
      - ./mongo-data:/data/db
      - ./mongo:/home/mongodb
      - ./init-db:/docker-entrypoint-initdb.d/
    ports:
      - '27017:27017'
    networks:
      - contact-network

networks:
  contact-network:
    driver: bridge